package me.ferdz.placeableitems.init;

import java.util.HashMap;

import me.ferdz.placeableitems.block.*;
import me.ferdz.placeableitems.block.tool.BlockSword;
import me.ferdz.placeableitems.block.tool.BlockTool;
import me.ferdz.placeableitems.tileentity.TEBase;
import me.ferdz.placeableitems.tileentity.TEClock;
import me.ferdz.placeableitems.tileentity.TEEdible;
import me.ferdz.placeableitems.tileentity.TEEdibleBiPosition;
import me.ferdz.placeableitems.tileentity.TEGoldenApple;
import me.ferdz.placeableitems.tileentity.TEPotion;
import me.ferdz.placeableitems.tileentity.TEStack;
import me.ferdz.placeableitems.tileentity.tool.TESword;
import net.minecraft.block.Block;
import net.minecraft.init.Items;
import net.minecraft.item.Item;
import net.minecraftforge.fml.common.registry.GameRegistry;

public class ModBlocks {

	public static HashMap<Item, BlockPlaceableItems> blockMap;

	public static Block blockLavaBucket, blockWaterBucket, blockMilkBucket, blockEmptyBucket;
	public static Block blockBook;
	public static Block blockBowl;
	public static Block blockBread;
	public static Block blockCarrot;
	public static Block blockApple, blockGoldenApple;
	public static Block blockArrow;
	public static Block blockPotato, blockPoisonedPotato;
	public static Block blockBeetroot, blockBeetrootSoup, blockBeetrootSeeds;
	public static Block blockBookAndQuill;
	public static Block blockBone;
	public static BlockPlaceableItems blockFish, blockSalmon, blockPufferfish, blockClownfish;
	public static Block blockBottleEmpty, blockPotion, blockExperienceBottle, blockSplashPotion;
	public static Block blockBow;
	public static Block blockCarrotOnStick;
	public static Block blockCookie;
	public static Block blockEgg;
	public static Block blockCoal;
	public static Block blockBrick, blockBrickNether;
	public static Block blockChorusFruit, blockChorusPopped;
	public static Block blockMelon, blockMelonGlistering;
	public static Block blockSword;
	public static Block blockClayBall;
	public static Block blockDiamond;
	public static Block blockChicken;
	public static Block blockFeather;
	public static Block blockIngot;
	public static Block blockEmerald;
	public static Block blockPumkinPie;
	public static Block blockDisc;
	public static Block blockFireCharge;
	public static Block blockCompass;
	public static Block blockWheat;
	public static Block blockBeef;
	public static Block blockPorkchop;
	public static Block blockSnowball;
	public static Block blockSlimeball;
	public static Block blockMutton;
	public static Block blockEnderPearl;
	public static Block blockLeather;
	public static Block blockSpiderEye;
	public static Block blockMagmaCream;
	public static Block blockFirework;
	public static Block blockClock;
	public static Block blockStick;
	public static Block blockBlazeRod;
	
	public static void init() {
		blockMap = new HashMap<Item, BlockPlaceableItems>();

		blockLavaBucket = new BlockFilledBucket("block_lava_bucket").setBucketItem(Items.LAVA_BUCKET).setItem(Items.LAVA_BUCKET).setBoundingBox(1, 0, 1, 15, 14, 15);
		blockWaterBucket = new BlockFilledBucket("block_water_bucket").setBucketItem(Items.WATER_BUCKET).setItem(Items.WATER_BUCKET).setBoundingBox(1, 0, 1, 15, 14, 15);
		blockMilkBucket = new BlockFilledBucket("block_milk_bucket").setBucketItem(Items.MILK_BUCKET).setItem(Items.MILK_BUCKET).setBoundingBox(1, 0, 1, 15, 14, 15);
		blockEmptyBucket = new BlockEmptyBucket("block_empty_bucket").setItem(Items.BUCKET).setBoundingBox(1, 0, 1, 15, 14, 15);
		blockBook = new BlockFaceable("block_book").setItem(Items.BOOK).setBoundingBox(2, 0, 2, 14, 3, 14);
		blockBowl = new BlockFaceable("block_bowl").setItem(Items.BOWL).setBoundingBox(2, 0, 2, 14, 3, 14);
		blockBread = new BlockEdible("block_bread", 5, 1.2F).setItem(Items.BREAD).setBoundingBox(2, 0, 2, 14, 5, 14);
		blockCarrot = new BlockBiPositionBiEdible("block_carrot", Items.CARROT, 3, 3.6F, Items.GOLDEN_CARROT, 6, 14.4F).setItem(Items.CARROT).setItem(Items.GOLDEN_CARROT).setBoundingBox(2, 0, 2, 14, 5, 14);
		blockApple = new BlockApple("block_apple", 4, 0.6F).setItem(Items.APPLE).setBoundingBox(3, 10, 3);
		blockGoldenApple = new BlockAppleGolden("block_apple_golden", 4, 2.4F).setItem(Items.GOLDEN_APPLE).setBoundingBox(3, 10, 3);
		blockArrow = new BlockArrow("block_arrow").setItem(Items.ARROW).setItem(Items.TIPPED_ARROW).setItem(Items.SPECTRAL_ARROW).setBoundingBox(1, 0, 1, 15, 4, 15);
		blockPotato = new BlockBiEdible("block_potato", Items.POTATO, 1, 0.6F, Items.BAKED_POTATO, 5, 1.44F).setItem(Items.POTATO).setItem(Items.BAKED_POTATO).setBoundingBox(3, 0, 3, 13, 7, 13);
		blockPoisonedPotato = new BlockPotatoPoisoned("block_potato_poisoned", 2, 0.6F).setItem(Items.POISONOUS_POTATO).setBoundingBox(3, 0, 3, 13, 7, 13);
		blockBeetroot = new BlockEdible("block_beetroot", 1, 1.2F).setItem(Items.BEETROOT).setBoundingBox(3, 0, 3, 13, 5, 13);
		blockBeetrootSoup = new BlockBeetrootSoup("block_beetroot_soup", 6, 1.2F).setItem(Items.BEETROOT_SOUP).setBoundingBox(2, 0, 2, 14, 3, 14);
		blockBeetrootSeeds = new BlockFaceable("block_beetroot_seeds").setItem(Items.BEETROOT_SEEDS).setBoundingBox(2, 0, 2, 14, 3, 14);
		blockBookAndQuill = new BlockBookAndQuill("block_book_and_quill").setItem(Items.WRITABLE_BOOK).setBoundingBox(0, 0, 0, 16, 5, 16);
		blockBone = new BlockBone("block_bone").setItem(Items.BONE).setBoundingBox(0, 0, 0, 16, 3, 16);
		blockFish = new BlockBiPositionBiEdible("block_fish", Items.FISH, 2, 0.2F, Items.COOKED_FISH, 5, 1.2F).setItem(Items.FISH).setItem(Items.COOKED_FISH).setBoundingBox(0, 0, 0, 16, 3, 16);
		blockSalmon = new BlockSalmon("block_salmon", Items.FISH, 2, 0.2F, Items.COOKED_FISH, 6, 1.6F).setItem(Items.FISH).setItem(Items.COOKED_FISH).setBoundingBox(0, 0, 0, 16, 3, 16);
		blockBottleEmpty = new BlockBiPosition("block_bottle_empty").setItem(Items.GLASS_BOTTLE).setBoundingBox(4, 0, 4, 12, 10, 12);
		blockPotion = new BlockPotion("block_potion").setItem(Items.POTIONITEM).setBoundingBox(4, 0, 4, 12, 10, 12);
		blockSplashPotion = new BlockSplashPotion("block_splash_potion").setItem(Items.SPLASH_POTION).setBoundingBox(4, 0, 4, 12, 10, 12);
		blockExperienceBottle = new BlockExperienceBottle("block_bottle_experience").setItem(Items.EXPERIENCE_BOTTLE).setBoundingBox(4, 0, 4, 12, 10, 12);
		blockBow = new BlockTool("block_bow").setItem(Items.BOW).setBoundingBox(0, 0, 0, 16, 4, 16);
		blockCarrotOnStick = new BlockTool("block_carrot_on_stick").setItem(Items.CARROT_ON_A_STICK).setBoundingBox(0, 0, 0, 16, 4, 16);
		blockCookie = new BlockEdible("block_cookie", 2, 0.2F).setItem(Items.COOKIE).setBoundingBox(3, 0, 3, 13, 4, 13);
		blockEgg = new BlockEgg("block_egg").setItem(Items.EGG).setBoundingBox(3, 0, 3, 13, 10, 13);
		blockCoal = new BlockCoal("block_coal").setItem(Items.COAL).setBoundingBox(3, 0, 3, 13, 10, 13);
		blockBrick = new BlockFaceable("block_brick").setItem(Items.BRICK).setBoundingBox(1, 0, 1, 15, 6, 15);
		blockBrickNether = new BlockFaceable("block_brick_nether").setItem(Items.NETHERBRICK).setBoundingBox(1, 0, 1, 15, 6, 15);
		blockChorusFruit = new BlockChorusFruit("block_chorus_fruit", 4, 2.4F).setItem(Items.CHORUS_FRUIT).setBoundingBox(2, 6, 2);
		blockChorusPopped = new BlockFaceable("block_chorus_popped").setItem(Items.CHORUS_FRUIT_POPPED).setBoundingBox(2, 6, 2);
		blockMelon = new BlockEdible("block_melon", 2, 1.2F).setItem(Items.MELON).setBoundingBox(5, 0, 1, 11, 14, 15);
		blockMelonGlistering = new BlockFaceable("block_melon_glistering").setItem(Items.SPECKLED_MELON).setBoundingBox(5, 0, 1, 11, 14, 15);
		blockSword = new BlockSword("block_sword").setItem(Items.WOODEN_SWORD).setItem(Items.STONE_SWORD).setItem(Items.IRON_SWORD).setItem(Items.GOLDEN_SWORD).setItem(Items.DIAMOND_SWORD);
		blockClayBall = new BlockFaceable("block_clay_ball").setItem(Items.CLAY_BALL).setBoundingBox(3, 0, 3, 13, 7, 13);
		blockDiamond = new BlockBiPosition("block_diamond").setItem(Items.DIAMOND).setBoundingBox(5, 0, 5, 11, 8, 11);
		blockChicken = new BlockChicken("block_chicken", Items.CHICKEN, 2, 1.2F, Items.COOKED_CHICKEN, 6, 7.2F).setItem(Items.CHICKEN).setItem(Items.COOKED_CHICKEN).setBoundingBox(1, 0, 1, 15, 8, 15);
		blockFeather = new BlockFaceable("block_feather").setItem(Items.FEATHER).setBoundingBox(3, 3, 3);
		blockIngot = new BlockIngot("block_ingot").setItem(Items.IRON_INGOT).setItem(Items.GOLD_INGOT).setBoundingBox(2, 4, 2);
		blockEmerald = new BlockBiPosition("block_emerald").setItem(Items.EMERALD).setBoundingBox(3, 10, 3);
		blockPumkinPie = new BlockEdible("block_pumpkin_pie", 8, 4.8F).setItem(Items.PUMPKIN_PIE).setBoundingBox(0, 6, 0);
		blockDisc = new BlockDisc("block_disc").setItem(Items.RECORD_11).setItem(Items.RECORD_13).setItem(Items.RECORD_BLOCKS).setItem(Items.RECORD_CAT).setItem(Items.RECORD_CHIRP).setItem(Items.RECORD_FAR).setItem(Items.RECORD_MALL).setItem(Items.RECORD_MELLOHI).setItem(Items.RECORD_STAL).setItem(Items.RECORD_STRAD).setItem(Items.RECORD_WAIT).setItem(Items.RECORD_WARD).setBoundingBox(3, 3, 3);
		blockFireCharge = new BlockFireCharge("block_fire_charge").setItem(Items.FIRE_CHARGE).setBoundingBox(2, 10, 2);
		blockCompass = new BlockCompass("block_compass").setItem(Items.COMPASS).setBoundingBox(3, 4, 3);
		blockWheat = new BlockFaceable("block_wheat").setItem(Items.WHEAT).setBoundingBox(1, 10, 1);
		blockBeef = new BlockBiPositionBiEdible("block_beef", Items.BEEF, 3, 1.8F, Items.COOKED_BEEF, 8, 12.8F).setItem(Items.COOKED_BEEF).setItem(Items.BEEF).setBoundingBox(2, 0, 2, 14, 5, 14);
		blockPorkchop = new BlockBiPositionBiEdible("block_porkchop", Items.PORKCHOP, 3, 0.6F, Items.COOKED_PORKCHOP, 8, 12.8F).setItem(Items.PORKCHOP).setItem(Items.COOKED_PORKCHOP).setBoundingBox(2, 0, 2, 14, 5, 14);
		blockSnowball = new BlockSnowball("block_snowball").setItem(Items.SNOWBALL).setBoundingBox(3, 0, 3, 13, 8, 13);
		blockSlimeball = new BlockSlimeball("block_slimeball").setItem(Items.SLIME_BALL).setBoundingBox(3, 0, 3, 13, 10, 13);
		blockPufferfish = new BlockPufferFish("block_puffer_fish", 1, 0.2F).setItem(Items.FISH).setBoundingBox(2, 9, 2);
		blockClownfish = new BlockClownFish("block_clown_fish", 1, 0.2F).setItem(Items.FISH).setBoundingBox(3, 4, 3);
		blockMutton = new BlockBiPositionBiEdible("block_mutton", Items.MUTTON, 2, 1.2F, Items.COOKED_MUTTON, 6, 9.6F).setItem(Items.MUTTON).setItem(Items.COOKED_MUTTON).setBoundingBox(0, 4, 0);
		blockEnderPearl = new BlockFaceable("block_ender_pearl").setItem(Items.ENDER_PEARL).setBoundingBox(3, 8, 3);
		blockLeather = new BlockFaceable("block_leather").setItem(Items.LEATHER).setBoundingBox(1, 5, 1);
		blockSpiderEye = new BlockFaceable("block_spider_eye").setItem(Items.SPIDER_EYE).setBoundingBox(2, 8, 2);
		blockMagmaCream = new BlockMagmaCream("block_magma_cream").setItem(Items.MAGMA_CREAM).setBoundingBox(2, 8, 2);
		blockFirework = new BlockFirework("block_firework").setItem(Items.FIREWORKS).setBoundingBox(3, 10, 3);
		blockClock = new BlockClock("block_clock").setItem(Items.CLOCK).setBoundingBox(0, 0, 0, 16, 16, 3);
		blockStick = new BlockRod("block_stick").setItem(Items.STICK);
		blockBlazeRod = new BlockBlazeRod("block_blaze_rod").setItem(Items.BLAZE_ROD);
		
		GameRegistry.registerTileEntity(TEBase.class, "te_base");
		GameRegistry.registerTileEntity(TEStack.class, "te_stack");
		GameRegistry.registerTileEntity(TEEdible.class, "te_edible");
		GameRegistry.registerTileEntity(TEGoldenApple.class, "te_golden_apple");
		GameRegistry.registerTileEntity(TESword.class, "te_sword");
		GameRegistry.registerTileEntity(TEEdibleBiPosition.class, "te_edible_biposition");
		GameRegistry.registerTileEntity(TEClock.class, "te_clock");
		GameRegistry.registerTileEntity(TEPotion.class, "te_potion");
	}
}
